# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e6b64a0fcd0bfcd9fee3ae80bca1aa68f200a0b1ded388e58270d5c49202c2b48724a520e646db4bff17ea968ee2b562fa1b85f1b98fb1b3543baa21379edc

test:
  secret_key_base: a214f83dcf9ce2b2447865b7c806dfe0526dede7a25aec6d3ea9db32cfd752e1a6d8bc4d9caf267599f4970fecabcc7bb2f07fb5ce9572c26bc276abadf10ff1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
